# Politique

-
  name: "franceinfo - Politique"
  group: "politique"
  feed: "https://www.francetvinfo.fr/politique.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Politique"
  group: "politique"
  feed: "https://france3-regions.francetvinfo.fr/politique/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Politique"
  group: "politique"
  feed: "https://la1ere.francetvinfo.fr/politique/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"

# Faits divers

-
  name: "franceinfo - Faits divers"
  group: "faitsdivers"
  feed: "https://www.francetvinfo.fr/faits-divers.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Faits divers"
  group: "faitsdivers"
  feed: "https://france3-regions.francetvinfo.fr/faits-divers/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Faits divers"
  group: "faitsdivers"
  feed: "https://la1ere.francetvinfo.fr/faits-divers/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
# -
#   name: "France Bleu - Infos"
#   group: "faitsdivers"
#   feed: "https://www.francebleu.fr/rss/infos.xml"
#   icon: "https://www.francebleu.fr/favicons/android-chrome-192x192.png"
-
  name: "TV5MONDE - Faits divers"
  group: "faitsdivers"
  feed: "https://information.tv5monde.com/afprss/francais--journal--faits-divers"
  icon: "https://www.tv5monde.com/cms/userdata/c_bloc/300/300076/300076_vignette_tv5-general.png"

# Société

-
  name: "franceinfo - Société"
  group: "societe"
  feed: "https://www.francetvinfo.fr/societe.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Société"
  group: "societe"
  feed: "https://france3-regions.francetvinfo.fr/societe/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Société"
  group: "politique"
  feed: "https://la1ere.francetvinfo.fr/societe/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"

# Économie

-
  name: "franceinfo - Économie"
  group: "economie"
  feed: "https://www.francetvinfo.fr/eco.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Économie"
  group: "economie"
  feed: "https://france3-regions.francetvinfo.fr/economie/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Économie"
  group: "economie"
  feed: "https://la1ere.francetvinfo.fr/economie/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "France 24 - Économie"
  group: "economie"
  feed: "https://www.france24.com/fr/economie/rss"
  icon: "https://www.france24.com/favicon-194x194.png"
-
  name: "RFI - Économie"
  group: "economie"
  feed: "https://www.rfi.fr/economie/rss"
  icon: "https://www.rfi.fr/favicon-194x194.png"

# Europe

-
  name: "franceinfo - Europe"
  group: "europe"
  feed: "https://www.francetvinfo.fr/europe.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 24 - Europe"
  group: "europe"
  feed: "https://www.france24.com/fr/europe/rss"
  icon: "https://www.france24.com/favicon-194x194.png"
-
  name: "RFI - Europe"
  group: "europe"
  feed: "https://www.rfi.fr/fr/europe/rss"
  icon: "https://www.rfi.fr/favicon-194x194.png"

# Monde

-
  name: "franceinfo - Afrique"
  group: "monde"
  feed: "https://www.francetvinfo.fr/afrique.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "franceinfo - Amériques"
  group: "monde"
  feed: "https://www.francetvinfo.fr/ameriques.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "franceinfo - Asie-Pacifique"
  group: "monde"
  feed: "https://www.francetvinfo.fr/asie-pacifique.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "franceinfo - Proche Orient"
  group: "monde"
  feed: "https://www.francetvinfo.fr/proche-orient.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 24 - Afrique"
  group: "monde"
  feed: "https://www.france24.com/fr/afrique/rss"
  icon: "https://www.france24.com/favicon-194x194.png"
-
  name: "France 24 - Moyen-Orient"
  group: "monde"
  feed: "https://www.france24.com/fr/moyen-orient/rss"
  icon: "https://www.france24.com/favicon-194x194.png"
-
  name: "France 24 - Amériques"
  group: "monde"
  feed: "https://www.france24.com/fr/ameriques/rss"
  icon: "https://www.france24.com/favicon-194x194.png"
-
  name: "France 24 - Asie Pacifique"
  group: "monde"
  feed: "https://www.france24.com/fr/asie-pacifique/rss"
  icon: "https://www.france24.com/favicon-194x194.png"
# -  
#   name: "Les Observateurs de France 24"
#   group: "monde"
#   feed: "https://observers.france24.com/fr/rss"
#   icon: "https://observers.france24.com/android-chrome-192x192.png"
-  
  name: "RFI - Afrique"
  group: "monde"
  feed: "https://www.rfi.fr/fr/afrique/rss"
  icon: "https://www.rfi.fr/favicon-194x194.png"
-
  name: "RFI - Moyen-Orient"
  group: "monde"
  feed: "https://www.rfi.fr/fr/moyen-orient/rss"
  icon: "https://www.rfi.fr/favicon-194x194.png"
-
  name: "RFI - Amériques"
  group: "monde"
  feed: "https://www.rfi.fr/fr/asie-pacifique/rss"
  icon: "https://www.rfi.fr/favicon-194x194.png"
- 
  name: "RFI - Asie Pacifique"
  group: "monde"
  feed: "https://www.rfi.fr/fr/ameriques/rss"
  icon: "https://www.rfi.fr/favicon-194x194.png"
-
  name: "TV5MONDE - Monde"
  group: "monde"
  feed: "https://information.tv5monde.com/afprss/francais--journal--mon"
  icon: "https://www.tv5monde.com/cms/userdata/c_bloc/300/300076/300076_vignette_tv5-general.png"
-
  name: "Outre-mer la 1ère - Océanie"
  group: "monde"
  feed: "https://la1ere.francetvinfo.fr/monde/ocean-pacifique/oceanie/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "Outre-mer la 1ère - Amérique du nord"
  group: "monde"
  feed: "https://la1ere.francetvinfo.fr/monde/ocean-atlantique/amerique-du-nord/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-  
  name: "Outre-mer la 1ère - Amérique du sud"
  group: "monde"
  feed: "https://la1ere.francetvinfo.fr/monde/ocean-atlantique/amerique-du-sud/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "Outre-mer la 1ère - Caraïbes"
  group: "monde"
  feed: "https://la1ere.francetvinfo.fr/monde/ocean-atlantique/caraibes/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "Outre-mer la 1ère - Asie"
  group: "monde"
  feed: "https://la1ere.francetvinfo.fr/monde/ocean-pacifique/asie/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"

# Culture

-
  name: "franceinfo - Culture"
  group: "culture"
  feed: "https://www.francetvinfo.fr/culture.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Culture"
  group: "culture"
  feed: "https://france3-regions.francetvinfo.fr/culture/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Culture"
  group: "culture"
  feed: "https://la1ere.francetvinfo.fr/culture/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "France Bleu - Culture"
  group: "culture"
  feed: "https://www.francebleu.fr/rss/culture.xml"
  icon: "https://www.francebleu.fr/favicons/android-chrome-192x192.png"
- 
  name: "France 24 - Culture"
  group: "culture"
  feed: "https://www.france24.com/fr/culture/rss"
  icon: "https://www.france24.com/favicon-194x194.png"
-
  name: "RFI - Culture"
  group: "culture"
  feed: "https://www.rfi.fr/culture/rss"
  icon: "https://www.rfi.fr/favicon-194x194.png"

# Sciences & Tech

-
  name: "franceinfo - Sciences"
  group: "sciencestech"
  feed: "https://www.francetvinfo.fr/sciences.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Sciences"
  group: "sciencestech"
  feed: "https://france3-regions.francetvinfo.fr/sciences/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Sciences"
  group: "sciencestech"
  feed: "https://la1ere.francetvinfo.fr/sciences/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "RFI - Sciences"
  group: "sciences"
  feed: "https://www.rfi.fr/science/rss"
  icon: "https://www.rfi.fr/favicon-194x194.png"
-
  name: "franceinfo - Tech & Web"
  group: "sciencestech"
  feed: "https://www.francetvinfo.fr/internet.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Technologies"
  group: "sciencestech"
  feed: "https://france3-regions.francetvinfo.fr/technologies/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Technologies"
  group: "sciencestech"
  feed: "https://la1ere.francetvinfo.fr/technologies/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"

# Santé

-
  name: "franceinfo - Santé"
  group: "sante"
  feed: "https://www.francetvinfo.fr/sante.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Santé"
  group: "sante"
  feed: "https://france3-regions.francetvinfo.fr/sante/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Santé"
  group: "sante"
  feed: "https://la1ere.francetvinfo.fr/sante/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "France 24 - Santé"
  group: "sante"
  feed: "https://www.france24.com/fr/sante/rss"
  icon: "https://www.france24.com/favicon-194x194.png"

# Sports

-
  name: "franceinfo - Sports"
  group: "sports"
  feed: "https://www.francetvinfo.fr/sports.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Sport"
  group: "sports"
  feed: "https://france3-regions.francetvinfo.fr/sport/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Sport"
  group: "sports"
  feed: "https://la1ere.francetvinfo.fr/sport/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "France Bleu - Sports"
  group: "sports"
  feed: "https://www.francebleu.fr/rss/sports.xml"
  icon: "https://www.francebleu.fr/favicons/android-chrome-192x192.png"
-
  name: "France 24 - Sport"
  group: "sports"
  feed: "https://www.france24.com/fr/sports/rss"
  icon: "https://www.france24.com/favicon-194x194.png"
-
  name: "RFI - Sport"
  group: "sports"
  feed: "https://www.rfi.fr/sports/rss"
  icon: "https://www.rfi.fr/favicon-194x194.png"

# Environnement

-
  name: "franceinfo - Environnement"
  group: "environnement"
  feed: "https://www.francetvinfo.fr/environnement.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Environnement"
  group: "environnement"
  feed: "https://france3-regions.francetvinfo.fr/environnement/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Environnement"
  group: "environnement"
  feed: "https://la1ere.francetvinfo.fr/environnement/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "France 24 - Planète"
  group: "environnement"
  feed: "https://www.france24.com/fr/planete/rss"
  icon: "https://www.france24.com/favicon-194x194.png"

# Animaux

-
  name: "franceinfo - Animaux"
  group: "animaux"
  feed: "https://www.francetvinfo.fr/animaux.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Animaux"
  group: "animaux"
  feed: "https://france3-regions.francetvinfo.fr/animaux/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Animaux"
  group: "animaux"
  feed: "https://la1ere.francetvinfo.fr/animaux/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "France 24 - Animaux"
  group: "animaux"
  feed: "https://www.france24.com/fr/animaux/rss"
  icon: "https://www.france24.com/favicon-194x194.png"

# Découvertes

-
  name: "franceinfo - Découvertes"
  group: "decouvertes"
  feed: "https://www.francetvinfo.fr/decouvertes.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 3 - Découvertes"
  group: "decouvertes"
  feed: "https://france3-regions.francetvinfo.fr/decouvertes/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Découvertes"
  group: "decouvertes"
  feed: "https://la1ere.francetvinfo.fr/decouverte/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"
-
  name: "France 24 - Découvertes"
  group: "decouvertes"
  feed: "https://www.france24.com/fr/decouvertes/rss"
  icon: "https://www.france24.com/favicon-194x194.png"
-
  name: "France Bleu - Vie quotidienne"
  group: "decouvertes"
  feed: "https://www.francebleu.fr/rss/vie-quotidienne.xml"
  icon: "https://www.francebleu.fr/favicons/android-chrome-192x192.png"

# Météo

-
  name: "France 3 - Météo"
  group: "meteo"
  feed: "https://france3-regions.francetvinfo.fr/meteo/rss"
  icon: "https://france3-regions.francetvinfo.fr/assets/img/icons/favicons/apple-touch-icon.png"
-
  name: "Outre-mer la 1ère - Météo"
  group: "meteo"
  feed: "https://la1ere.francetvinfo.fr/meteo/rss"
  icon: "https://la1ere.francetvinfo.fr/assets/img/icons/favicons_outremer/android-chrome-192x192.png"

# Fact-cheking

-
  name: "franceinfo - Vrai ou fake"
  group: "factchecking"
  feed: "https://www.francetvinfo.fr/vrai-ou-fake.rss"
  icon: "https://www.francetvinfo.fr/skin/dist/mobile/img/pwa/launcher-76x76-832d6cb324.png"
-
  name: "France 24 - Les observateurs - Intox"
  group: "factchecking"
  feed: "https://observers.france24.com/fr/tag/intox/rss"
  icon: "https://observers.france24.com/android-chrome-192x192.png"